export {
  defineInfiniteQuery,
  defineMutation,
  defineQuery,
  error,
  fieldErrorMessage,
  formatDalError,
  formSubmitMessage,
  fromPostgrestError,
  fromZodError,
  isDalError,
  mutate,
  mutateAsResult,
  pageEnvelopeSchema,
  query,
  queryInfinite,
  success,
  toFormErrors,
  toInfiniteQueryOptions,
  toMutationOptions,
  toPaginatedQueryOptions,
  toQueryOptions,
  unknownError,
} from './core';

export type {
  ClientStrategy,
  DalEntity,
  DalError,
  DalResult,
  FormSubmitErrors,
  InfiniteQueryDef,
  MutationDef,
  PageEnvelope,
  PostgrestErrorLike,
  QueryCallOptions,
  QueryDef,
  SupabaseQueryResult,
  ValidationIssue,
} from './core';

export { getQueryClient } from './get-query-client';
